print("------------------")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("Python has entered the building")
print("-----------------")